### ISSUE TITLE
Only works on api 21

### ISSUE THREAD

**Issue by aitor19rp** [SilleBille/DynamicCalendar#1]
Hi! I just get to work it on api 21, I have tryied on lows API's and it doesn't work, What I have to do?

**Comment by SilleBille** [comment]
Hi dilux. All you need to do is, set the minimum SDK version to 8 or 9. Then sync the gradle files. It should run.

If issue persists, can you share the log?

**Comment by aitor19rp** [comment]
thanks and sorry I'm having a problem with another library, thank for answer!

**Comment by SilleBille** [comment]
No probs! All the best with your app :+1:
